export const normalizeProject = (project) => ({
    id: String(project.id || project.Id || ''),
    title: project.title || project.Title || 'Projet inconnu',
    description: project.description || project.Description || '',
    methodology: project.methodology || project.Methodology || '',
    createdAt: project.createdAt || project.CreatedAt || new Date().toISOString(),
    startDate: project.startDate || project.StartDate || new Date().toISOString(),
    endDate: project.endDate || project.EndDate || new Date().toISOString(),
    createdBy: project.createdBy || project.CreatedBy || '',
    projectManagers: project.projectManagers || project.ProjectManagers || [],
    productOwners: project.productOwners || project.ProductOwners || [],
    scrumMasters: project.scrumMasters || project.ScrumMasters || [],
    users: project.developers || project.Developers || [],
    testers: project.testers || project.Testers || [],
    observers: project.observers || project.Observers || [],
  });